---
title: Creating a website with the academic theme in blogdown
author: Kevin Zolea
date: '2019-02-13'
slug: Creating-a-website-with-the-academic-theme-in-blogdown
categories:
  - blogdown
  - R
  - Hugo
tags:
  - blogdown
  - R
summary: My thoughts and some guidance on how to set up a free website with blogdown, GitHub, and Netlify

image: 
  caption: ''
  focal_point: ''
---



## Introduction:
For years now I have been contemplating developing my first personal website. I have been told by a countless number of people that it is a great way to showcase your skills and tell your story. I have been meaning to make one for some time now but I kept coming up with excuses. The two biggest excuses I kept telling myself was that it would be too difficult & it would cost money. Boy was I wrong. It wasn't until I started using R this past year that I realized how wrong I was. After a quick google search I came across the [blogdown](https://cran.r-project.org/web/packages/blogdown/blogdown.pdf) package. Blogdown is an amazing package in which you can create blogs and websites with [R Markdown](https://rmarkdown.rstudio.com/). Now I'm not saying that this stuff is extremely easy but if someone like myself(absolutely no website development knowledge) can do it, **YOU CAN TOO!** This blog post isn't a sure fire way to do it but more of an overview of how I did it. I would also like to point out that this is a **very basic introduction ** to creating a blog/website with blogdown. The amount of things you can do with this package is almost endless.. especially if you have an understanding of CSS, HTML, and Javascript.


## Prerequisites:
Before you jump right in I recommend reading some online material and watching some youtube videos. Here is a list of the resources that helped me a lot.
1.[blogdown: Creating Websites with R Markdown](https://bookdown.org/yihui/blogdown/)

2.[Up and Running with Blogdown](https://alison.rbind.io/post/up-and-running-with-blogdown/)

3.[Making a Website with Blogdown](https://www.youtube.com/watch?v=syWAKaj-4ck&t=649s)

4.[Academic Theme Documentation](https://sourcethemes.com/academic/docs/) if your going to use the academic theme


