---
title: Air quality & the COVID-19 crisis in NJ
author: Kevin Zolea
date: '2020-04-13'
slug: air-quality-the-COVID-19-crisis-in-nj
categories:
  - R
  - air quality
tags:
  - R
  - air quality
image:
  caption: ''
  focal_point: ''
---
# Introduction

Since my last post, I have seen some articles in the media discussing the link between COVID-19 and air quality. Being that I work for the [Bureau of Air Monitoring ](http://njaqinow.net){target="_blank"}, I felt like it would only be right to perform my own analysis on the vast amount of data we collect. If you'd like to read over some of the above mentioned articles you can find them at the following links:

* [New Jersey's poor air quality expected to improve significantly amid coronavirus shutdown](https://www.northjersey.com/story/news/coronavirus/2020/03/25/nj-coronavirus-states-air-quality-expected-rebound-amid-shutdown/2905998001/){target="_blank"}

* [N.J.'s air is the cleanest it’s been since 9/11 due to coronavirus shutdown](https://www.nj.com/coronavirus/2020/04/njs-air-is-the-cleanest-its-been-since-911-due-to-coronavirus-shutdown.html){target="_blank"}

* [N.J.'s coronavirus death toll is likely higher thanks to decades of dirty air](https://www.nj.com/coronavirus/2020/04/njs-coronavirus-death-toll-is-likely-higher-thanks-to-decades-of-dirty-air.html){target="_blank"}

# Motivation for this post

I received a message from an old collegue of mine asking if I had taken a look at the air quality since the crisis started. This got me thinking about how I can use the power of R to create some plots and maps of the change of air quality throughout the state. I will be taking a look at a few of the criteria air pollutants at some of our major sites. 

# What are criteria air pollutants?

[Criteria air pollutants](https://www.epa.gov/criteria-air-pollutants){target="_blank"} are six common air pollutants of concern. The criteria pollutants are carbon monoxide, lead, nitrogen dioxide, ozone, particulate matter, and sulfur dioxide. These criteria air pollutants can cause health effects to the population at certain exposure levels. The Clean Air Act requires the [Environmental Protection Agency](https://www.epa.gov){target="_blank"} (EPA) to set standards called the [National Ambient Air Quality Standards](https://www.epa.gov/criteria-air-pollutants/naaqs-table){target="_blank"} (NAAQS) to limit the concentrations of these six criteria pollutants.

# What does any of this have to do with COVID-19?







